//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace prj1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class TableMembers1081640
    {
        [DisplayName("個人ID")]
        [Required]
        [RegularExpression("^[0-9]*$",ErrorMessage ="只能輸入數字")]
        public string fId { get; set; }

        [DisplayName("帳號")]
        [Required(ErrorMessage = "帳號不可空白")]
        [RegularExpression("^[A-Za-z0-9]+$", ErrorMessage ="只能輸入英文和數字")]
        public string fUserId { get; set; }

        [DisplayName("密碼")]
        [Required]
        [StringLength(8, ErrorMessage = "密碼必須是6~18個數字", MinimumLength = 6)]
        [RegularExpression("^[0-9]*$", ErrorMessage = "只能輸入數字")]
        public string fPwd { get; set; }

        [DisplayName("姓名")]
        [Required]
        [RegularExpression("^[A-Za-z]+$", ErrorMessage ="只能輸入英文名字")]
        public string fName { get; set; }

        [DisplayName("信箱")]
        [Required]
        [EmailAddress(ErrorMessage = "E-Mail格式有誤")]
        public string fEmail { get; set; }
    }
}
